version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: healthtech
      ME_CONFIG_BASICAUTH_PASSWORD: HealthTech2020
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: adm
      ME_CONFIG_MONGODB_ADMINPASSWORD: HealthTech2020
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm
      MONGO_INITDB_ROOT_PASSWORD: HealthTech2020
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db